name: Checks

on: [push, pull_request]

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install deps
        run: poetry install
      - name: Test
        run: make test
      - uses: codecov/codecov-action@v3
        with:
          files: ./.coverage
          fail_ci_if_error: true