name: Checks

on: [push, pull_request]

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install
      - name: Test
        run: make test